[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "libsrt"
version = "0.1.0"
description = "High performance Rust port of byroot/pysrt"
authors = [{name = "K.Anirudh Reddy", email = "anirudhreddykallem2008@gmail.com"}]
requires-python = ">=3.8"

[tool.maturin]
features = ["python", "extension-module"]
module-name = "libsrt"

[tool.pytest.ini_options]
testpaths = ["tests/fixed"]
